<a href="https://colab.research.google.com/github/rafaelmgr12/UNIVESP-AlgeProg1/blob/master/Lectures_on_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Lectures


1. List vs Array


In [ ]:
import numpy as np

In [ ]:
L = [1,2,3] 
A = np.array([1,2,3])

In [ ]:
for e in L:
    print(e)

1
2
3


In [ ]:
# Test now with the array
for e in A:
    print (e)

1
2
3


Try use the command append


In [ ]:
L.append(4)
print(L)

[1, 2, 3, 4]


In [ ]:
A.append(4)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

Another for to append a list

L = L + [5]
print (L)

We can't add either in a numpy array. 

In the end we see that a numpy.array is more like with the a mathematical vector. So we can treat them as vector in the usual way. We can treat a list, usually, as array but with some operations is limited 


# Dot product 1: For loop vs. cosine method vs. dot function

In [ ]:
a = np.array([1,2])
b = np.array([2,1])
dot = 0

Use now the loop to compute the dot product

In [ ]:
for e, f in zip(a,b): 
    dot += e*f
dot

4

In [ ]:
a*b

array([2, 2])

In [ ]:
np.sum(a*b)

4

In [ ]:
(a*b).sum()

4

To compute the magnitude, we can use

In [ ]:
amag = np.sqrt((a*a).sum())
amag

2.23606797749979

The numpy has a libary with the linear algebra function

In [ ]:
amag = np.linalg.norm(a)
amag

2.23606797749979

## The final lesson is don't use loop, avoid them

# Vector and Matrices

In [ ]:
M = np.array([[1,2],[3,4]])
L = [[1,2],[3,4]]

In [ ]:
L[0]

[1, 2]

In [ ]:
L[0][0]

1

In [ ]:
M[0][0]

array([[1, 2],
       [3, 4]])

In [ ]:
M

array([[1, 2],
       [3, 4]])

In [ ]:
# compute the transpose
M.T


array([[1, 3],
       [2, 4]])

# Generating a Matrices to work with

Create a array, not manualy


In [ ]:
z = np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
z = np.zeros((10,10))
z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
# Random array
R = np.random.random((10,10))
R

array([[0.5563749 , 0.9942094 , 0.44054144, 0.08217564, 0.4148066 ,
        0.74412199, 0.93352681, 0.40792733, 0.12450601, 0.27313407],
       [0.02329446, 0.45260816, 0.59238853, 0.84741424, 0.68699749,
        0.65537731, 0.32310189, 0.81462542, 0.24179918, 0.05851397],
       [0.75048594, 0.43480089, 0.61404133, 0.65108668, 0.43880403,
        0.53158199, 0.37650396, 0.34754459, 0.77911677, 0.82157389],
       [0.33099413, 0.18794647, 0.87481553, 0.71602536, 0.27821003,
        0.52628232, 0.87555413, 0.79981728, 0.62396849, 0.67257855],
       [0.50062125, 0.57032071, 0.22422664, 0.78734058, 0.39012615,
        0.62322702, 0.94312343, 0.86897585, 0.84138509, 0.41306359],
       [0.23169961, 0.3576786 , 0.0358108 , 0.11681459, 0.53962137,
        0.65745414, 0.1183737 , 0.43749095, 0.74740526, 0.19457185],
       [0.77860288, 0.28360487, 0.10787378, 0.68301382, 0.9590075 ,
        0.83454438, 0.04163059, 0.9393037 , 0.90679731, 0.30878781],
       [0.7790086 , 0.69241848, 0.1555934

In [ ]:
# Gaussian distribution
G = np.random.randn(10,10)
G 

array([[ 1.2600907 , -0.30899376, -0.28432851, -0.70829656, -2.03737401,
         1.50811744,  2.0394837 , -1.43798171,  0.48905186, -0.21214823],
       [ 0.12264946, -1.05536362,  0.05016926, -0.9791378 ,  0.66511724,
         0.25603227,  1.62237125,  0.11305985, -1.78284012,  0.21704669],
       [-1.55515095,  1.38006765,  0.833317  ,  0.64389896,  1.20091647,
         0.45110016, -0.84275609, -1.59485422,  1.00296555, -0.78247655],
       [-0.87622496, -0.56036263,  0.2069844 , -0.2488609 ,  0.31406327,
         1.71908995,  0.68528649, -0.38448321,  0.84910092, -1.43069694],
       [ 0.15422765, -1.22984895, -1.19659823, -0.08905001,  0.63962865,
        -0.31461862, -1.15830565, -0.78430167, -0.43483729, -1.63472969],
       [ 0.09275263,  0.09087521,  1.3929901 ,  0.2344836 , -1.18737623,
         0.2805451 ,  0.17045721, -0.99120948, -0.94586465, -0.3271905 ],
       [-1.58636007, -0.79214187,  1.03031712, -0.11041241, -1.9216464 ,
        -0.9184821 ,  1.18793441, -0.24568134

In [ ]:
G.mean()

-0.17629440106395908

In [ ]:
G.var()

0.9935652623166069

# Matrix operation

In [ ]:
# inverse

A = np.array([[1,2],[3,4]])
print (A)
print ("\n")

Ainv = np.linalg.inv(A)
print (Ainv)

[[1 2]
 [3 4]]


[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
Ainv.dot(A) #test the inverse

array([[[[1.00000000e+00, 0.00000000e+00]],

        [[2.22044605e-16, 1.00000000e+00]]]])

In [ ]:
# determiant
np.linalg.det(A)

array([-2.])

In [ ]:
np.diag(A)

array([1, 4])

Now we will make a fake dataset to compute de eigenvectors and eivenvalues

In [ ]:
X = np.random.randn(100,3)
cov = np.cov(X)#wrong, 


In [ ]:
cov.shape

(100, 100)

In [ ]:
cov = np.cov(X.T)

In [ ]:
cov

NameError: name 'cov' is not defined

$\alpha$